accelerator: ddp
batch_size: 1000
c: modules/cnn/config/config_feature_extract.yml
check_val_every_n_epoch: 1
ckpt_path: /home/jovyan/Adv.CV/TeCNO_ver2/TeCNO/logs/250615-191533_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model/checkpoints/250615-191533_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Modelepoch=4-val_acc_phase=0.83.ckpt
data_root: /home/jovyan/Adv.CV/TeCNO_ver2/TeCNO/cholec80_processed
dataset: cholec80_feature_extract.Cholec80FeatureExtract
dataset_mode: img_multilabel
early_stopping_metric: val_acc_phase
fast_dev_run: false
fps_sampling: 25.0
fps_sampling_test: 25.0
gpus:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
input_height: 224
input_width: 224
learning_rate: 0.0005
log_every_n_steps: 50
log_interval: 100
log_save_interval: 100
max_epochs: 15
min_epochs: 6
model: cnn.TwoHeadResNet50Model
model_specific_batch_size_max: 80
module: cnn.feature_extraction.FeatureExtraction
name: null
num_sanity_val_steps: 4
num_tasks: 2
num_workers: 10
on_polyaxon: false
optimizer_name: adam
out_features: 7
output_path: !!python/object/apply:pathlib.PosixPath
- /
- home
- jovyan
- Adv.CV
- TeCNO_ver2
- TeCNO
- logs
- 250615-191533_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model
overfit_pct: 0.0
pretrained: true
resume_from_checkpoint: null
row_log_interval: 100
save_top_k: 1
test_extract: true
test_percent_check: 1.0
train_percent_check: 1.0
val_percent_check: 1.0
